#!/bin/bash

startup=./data/iniciar
monitorizar=./data/monitorizar
iniciarCliente=./data/cliente

start() {
	if find /var/lock/iniciar 2> error.txt; then
		 echo "Ya ha sido creado anteriormente el servicio.\nNO PUEDE INICIARSE UN SEGUNDO DEMONIO, puede parar, monitorear una carpeta o cambiar el tiempo de sincronizacion" >&2
		 exit 1
	else
		echo "Arrancando servicio"
		mkdir /var/lock/iniciar 2> error.txt
		$startup
	fi
}

iniciarCliente() {
	if(find /var/lock/iniciar 2> error.txt) ; then 
		shift
		echo -n "Iniciando cliente"
		$iniciarCliente $@
	else 
		echo -n "Error, no se ha iniciado el demonio todavia"
	fi
}

iniciarServidor() {
	if(find /var/lock/iniciar 2> error.txt) ; then 
		shift
		echo -n "Iniciando servidor"
		$iniciarServidor $@
	else 
		echo -n "Error, no se ha iniciado el demonio todavia"
	fi
}

monitorizar() {
	if(find /var/lock/iniciar 2> error.txt) ; then 
		
		shift
		carpetas=""
		while [ "$1" != "" ]; do
			echo "$1"
		 #Filtrando monitorizar
	    	carpetas+="$1" 
	    	carpetas+=" "
	    	shift
		done
		
		#echo  "Se va a monitorizar las carpetas:" $carpetas
		$monitorizar $carpetas
		
	else 
		echo -n "Error, no se ha iniciado el demonio todavia"
	fi
}

stop() {
	echo "Parando servicio"
	
	pkill -f iniciar
	
	if(find /var/lock/iniciar 2> error.txt) ; then 
		rmdir /var/lock/iniciar 
	fi
	
	#Cuando cerramos hay que hacer la ultima conexion de datos al servidor
	data/cliente localhost 8888 estadisticasCliente.txt;
	echo "Borrando ultimas estadisticas"
	rm estadisticasCliente.txt;
	rm error.txt
}

case "$1" in
	start)
		start
	;;
	monitorizar)
		#echo "Vamos a monitorizar"
		#echo  "Parametros: " $@
		#echo  "Se monitorizara las carpetasLlegue hasta aqui," $# " argumentos\n"
		monitorizar $@
	;;
	stop)
		stop
	;;
	iniciarCliente)
		iniciarCliente $@
	;;
	iniciarServidor)
		iniciarServidor $@
	;;
	*) echo "Opcion no permitida"
		exit 1
esac

exit 0
